# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: 
  - 12
cache: npm

# 指定博客源码分支，因人而异。hexo博客源码托管在独立repo则不用设置此项
branches:
  only:
    - source 

# 执行清缓存，生成网页操作
script:
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后deploy部署
after_script:
  - git config user.name "zenglixing0822"
  - git config user.email "cenglihang@163.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# End: Build LifeCycle